default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['TNTBOT_DB_HOST'] %>
  port: <%= ENV['TNTBOT_DB_PORT'] %>
  database: <%= ENV['TNTBOT_DB_NAME'] %>
  username: <%= ENV['TNTBOT_DB_USERNAME'] %>
  password: <%= ENV['TNTBOT_DB_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
